name: Init repo for a cargo crate workflow
description: 'Initialize the workflow for a cargo crate (i.e.\ checkout repo, cache cargo, install rust)'
inputs:
  profile:
    description: 'Profile to use (minimal \/ default)'
    required: true
    default: 'minimal'
  toolchain:
    description: 'Toolchain to install (stable \/ beta \/ nightly \/ <specific version>)'
    required: true
    default: 'stable'
  components:
    description: '(Optional) Toolchain components to install (e.g., rustfmt, clippy)'
    required: false
  override:
    description: '(Optionally) Whether or not to override the default toolchain'
    required: false
  cache-key-prefix:
    description: '(Optional) Prefix for caching key'
    required: false
    default: '${{ runner.os }}-'
  only_cache:
    description: 'Only do the caching pass, not the installation'
    required: false
    default: "false"
  token:
    description: 'GitHub token to use for checking out the repository'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      if: inputs.only_cache != true || inputs.only_cache != 'true'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ inputs.token }}

    - name: Cache Cargo Directories
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: ${{ inputs.cache-key-prefix }}

    - name: Install Rust
      if: inputs.only_cache != true || inputs.only_cache != 'true'
      uses: orgrinrt/cicd/.github/actions/install_rust@main
      with:
        profile: ${{ inputs.profile }}
        toolchain: ${{ inputs.toolchain }}
        override: ${{ inputs.override }}
        components: ${{ inputs.components }}
