name: Install Rust
description: 'Install the Rust toolchain'
inputs:
  profile:
    description: 'Profile to use (minimal \/ default)'
    required: true
    default: 'minimal'
  toolchain:
    description: 'Toolchain to install (stable \/ beta \/ nightly \/ <specific version>)'
    required: true
    default: 'stable'
  components:
    description: 'Comma‑separated list of components to install (e.g., rustfmt, clippy)'
    required: false
    default: ''
  override:
    description: 'Whether to override the default toolchain (true or false)'
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: ${{ inputs.profile }}
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        override: ${{ inputs.override }}
